library(tidyverse)
library(httr2)
library(jsonlite)
library(rvest)
library(janitor)
library(stringr)
library(readr)

dir.create("data/raw", recursive = TRUE, showWarnings = FALSE)
dir.create("data/processed", recursive = TRUE, showWarnings = FALSE)
dir.create("data/validation", recursive = TRUE, showWarnings = FALSE)
dir.create("outputs/summary_tables", recursive = TRUE, showWarnings = FALSE)
dir.create("outputs/figures", recursive = TRUE, showWarnings = FALSE)
